export const COMBAT_CONFIG = {
  timeEpsilon: 1e-9,
  hudUpdateInterval: 0.1,
  bindings: { front: 'Space', left: 'KeyQ', right: 'KeyE', repair: 'KeyR' },
  player: { maxHp: 100, damage: 30, sideDamage: 15, frontCooldown: 1, sideCooldown: 1.5 },
  collision: { maxDamage: 5, cooldown: 1 },
  repair: { cooldown: 30, duration: 5, rate: 10, maxHealing: 50 },
  enemyVisionRange: 300,
  enemyReturnVisionRange: 90,
  chaser: { maxHp: 40, contactDamage: 40, speed: 120, rotationSpeed: 120 * Math.PI / 180 },
  shooter: { maxHp: 60, damage: 10, speed: 92, rotationSpeed: 100 * Math.PI / 180,
    attackRange: 220, frontCooldown: 1.8, sideCooldown: 3,
    frontAimTolerance: 0.03, sideAimTolerance: 0.08 },
  projectile: { radius: 4, playerSpeed: 520, enemySpeed: 380, lifetime: 3,
    maxStep: 4, spriteScale: 0.8, playerFrontSizeMultiplier: 1.8, playerFrontRange: 360 },
  weapons: { frontOffset: 52.8, sideOffset: 24, broadsideOffsets: [-44.8, 0, 44.8] },
  spawn: { areaCount: 24, maxPopulation: 43, areaSize: 640, areaAttempts: 1000, positionAttempts: 64,
    playerSafeDistance: 450, initialAreaSafeDistance: 650,
    respawnInterval: 12, retryInterval: 2, seedSalt: 0x51f15e },
  patrol: { destinationAttempts: 32, lookAhead: 36, leashMargin: 750, safetyMargin: 16, minRadius: 72, hullLookAhead: 100 },
  avoidance: { neighborRange: 110, separationWeight: 2.5, lateralWeight: 0.8, attackSpeedFactor: 0.5 },
  obstacles: { probeStep: 12, probePadding: 4, clearance: 22, orbitStep: Math.PI / 8,
    stuckSeconds: 1, progressSpeedRatio: 0.1, goalReleaseDistance: 40 },
  effects: { shotDuration: 0.12, impactDuration: 0.22, explosionDuration: 0.65, sinkingDuration: 3,
    shotScale: 1, impactScale: 0.6, explosionScale: 0.9 },
} as const
