export const COMBAT_CONFIG = {
  timeEpsilon: 1e-9,
  hudUpdateInterval: 0.1,
  bindings: { front: 'Space', left: 'KeyQ', right: 'KeyE', repair: 'KeyR' },
  player: { maxHp: 100, damage: 30, sideDamage: 15, frontCooldown: 1, sideCooldown: 1.5 },
  collision: { maxDamage: 5, islandMinDamageSpeed: 176, contactReleaseGap: 8 },
  repair: { cooldown: 30, duration: 5, rate: 10, maxHealing: 50 },
  enemyVisionRange: 345,
  enemyReturnVisionRange: 90,
  chaser: { maxHp: 40, contactDamage: 40, speed: 120, rotationSpeed: 120 * Math.PI / 180, maxBoost: 0.3, predictionSeconds: 0.6, targetSmoothing: 3, headingDeadband: 0.08, impactDistance: 130 },
  shooter: { maxHp: 60, damage: 10, speed: 92, rotationSpeed: 100 * Math.PI / 180,
    attackRange: 220, frontCooldown: 1.8, sideCooldown: 3,
    frontAimTolerance: 0.03, sideAimTolerance: 0.12, maneuverSeconds: 3, orbitRadius: 190, radialGain: 1.5, sideProjectileCount: 3 },
  projectile: { radius: 4, playerSpeed: 520, enemySpeed: 380, lifetime: 3,
    maxStep: 4, spriteScale: 0.8, playerFrontSizeMultiplier: 1.8, playerHitRadiusMultiplier: 1.25, playerFrontRange: 360, playerSideRange: 300 },
  weapons: { frontOffset: 52.8, sideOffset: 24, playerFrontOffset: 59.4, playerSideOffset: 27, broadsideOffsets: [-44.8, 0, 44.8] },
  spawn: { areaCount: 24, maxPopulation: 43, areaSize: 640, areaAttempts: 1000, positionAttempts: 64,
    playerSafeDistance: 450, initialAreaSafeDistance: 650,
    respawnInterval: 12, retryInterval: 2, seedSalt: 0x51f15e },
  patrol: { destinationAttempts: 32, lookAhead: 36, leashMargin: 750, safetyMargin: 3, minRadius: 72, hullLookAhead: 100 },
  avoidance: { neighborRange: 160, predictionSeconds: 1.2, minimumRouteProjection: 0.5, minimumSpeedFactor: 0.22, commitmentSeconds: 1.2, separationWeight: 2.5, priorityWeight: 0.35, headOnDot: -0.5 },
  obstacles: {
    routeCell: 32, routeRefreshSeconds: 0.75, goalMoveThreshold: 60,
    connectorCells: 3, routeSwitchRatio: 0.1, routeSwitchDistance: 24,
    waypointHullRatio: 0.5, waypointStepFactor: 2,
    turnProbeAngle: Math.PI / 24, escapeStep: 16, escapeDistance: 640, escapeSpeedFactor: 0.45,
    turnGraceSeconds: 1.8, stuckSeconds: 2.5, progressDistance: 6, progressSpeedRatio: 0.1 },
  effects: { shotDuration: 0.12, impactDuration: 0.22, explosionDuration: 0.65, sinkingDuration: 3,
    shotScale: 1, impactScale: 0.6, explosionScale: 0.9, splashDuration: 0.45, trailLength: 14 },
} as const
