export const GAME_CONFIG = {
  worldWidth: 4000,
  worldHeight: 4000,
  playerSpeed: 176,
  straightSailing: { distanceForMaxBoost: 300, maxBoost: 0.3 },
  playerRotationSpeed: 240 * Math.PI / 180,
  // Hull circles in ship_1's native pixels, relative to the sprite's center.
  playerHullCircles: [
    { x: 0, y: -36, radius: 9 },
    { x: 0, y: -24, radius: 13 },
    { x: 0, y: -8, radius: 16 },
    { x: 0, y: 8, radius: 16 },
    { x: 0, y: 24, radius: 13 },
    { x: 0, y: 40, radius: 9 },
    { x: 0, y: 48, radius: 5 },
  ],
  camera: { mobileZoom: 0.7, mobileMaxSide: 1024, mobileShortSide: 600 },
  playerSpriteScale: 0.9,
  enemySpriteScale: 0.8,
  decoration: { densityMin: 0.65, densityMax: 1.15, largePlantChance: 0.22, largePlantMultiplier: 1.35,
    largeRockChance: 0.25, largeRockMultiplier: 1.5, clusterRadius: 75 },
  spriteRotationOffset: Math.PI,
  islandMinCount: 30,
  islandMaxCount: 42,
  islandMinSize: 200,
  islandMaxSize: 860,
  islandOutlinePoints: 32,
  islandTextureSize: 512,
  islandVegetationInset: 0.72,
  audio: { defaultVolume: 0.45, maxVoices: 8, eventGapMs: 55, ambienceVolume: 0.18 },
  debugColliders: false,
  islandMinDistance: 140,
  spawnSafeRadius: 400,
  placementAttempts: 5000,
  islandLayout: { attempts: 24, compactAt: [12, 18], sizeRangeFactor: 0.5 },
  movementStep: 8,
  oceanTileScale: 0.5,
} as const
